# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fmc-arc-portal-contianer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a26f9fcc27fd451397aa4512f8e81868 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3dad20ad11c94343ba2300d4509d5bdb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a26f9fcc27fd451397aa4512f8e81868 }}/fmc/arc-portal:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fmc-arc-portal-contianer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_80ff4c2fdde04572a0b71b531a26538c }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a26f9fcc27fd451397aa4512f8e81868 }}/fmc/arc-portal:${{ github.sha }}'